app/hr/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required

from hr import views

urlpatterns = patterns('',
    url('^$', login_required(views.HrIndexView.as_view()), name='hr-index'),

    url(r'^application/$', login_required(views.HrViewUserApplications.as_view()), name='hr-userapplications'),
    url(r'^application/(?P<slug>\d+)/$', login_required(views.HrViewApplication.as_view()), name='hr-viewapplication'),
    url(r'^application/(?P<slug>\d+)/update/(?P<status>\d+)/$', login_required(views.HrUpdateApplication.as_view()), name='hr-updateapplication'),
    url(r'^application/(?P<applicationid>\d+)/note/$', login_required(views.HrAddNote.as_view()), name='hr-addnote'),
    url(r'^application/(?P<applicationid>\d+)/message/$', login_required(views.HrAddMessage.as_view()), name='hr-addmessage'),
    url(r'^application/(?P<applicationid>\d+)/reject/$', login_required(views.HrRejectApplication.as_view()), name='hr-rejectapplication'),
    url(r'^application/(?P<applicationid>\d+)/accept/$', login_required(views.HrAcceptApplication.as_view()), name='hr-acceptapplication'),
    url(r'^application/add/$', login_required(views.HrAddApplication.as_view()), name='hr-addapplication'),
    url(r'^application/admin/$', login_required(views.HrAdminApplications.as_view()), name='hr-admin'),

    url(r'^recommendation/$', login_required(views.HrViewRecommendations.as_view()), name='hr-viewrecommendations'),
    url(r'^recommendation/add/$', login_required(views.HrAddRecommendation.as_view()), name='hr-addrecommendation'),

    url(r'^blacklist/$', login_required(views.HrBlacklistList.as_view()), name='hr-blacklist-list'),
    url(r'^blacklist/add/$', login_required(views.HrAddBlacklist.as_view()), name='hr-blacklist-add'),
    url(r'^blacklist/add/user/(?P<userid>\d+)/$', login_required(views.HrBlacklistUser.as_view()), name='hr-blacklistuser'),
)

app/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from utils import installed
from registration.views import register
from sso.forms import RegistrationFormUniqueEmailBlocked


admin.autodiscover()

urlpatterns = patterns('',
    ('', include('registration.backends.default.urls')),
    (r'^register/$', register, {'backend': 'registration.backends.default.DefaultBackend', 'form_class': RegistrationFormUniqueEmailBlocked}),
    ('', include('sso.urls')),
    (r'^eve/', include('eve_api.urls')),
    (r'^eveapi/', include('eve_proxy.urls')),
    (r'^api/', include('api.urls')),
)

if installed('reddit'):
    urlpatterns += patterns('',
        ('', include('reddit.urls')),
    )

if installed('hr'):
    urlpatterns += patterns('',
        (r'^hr/', include('hr.urls')),
    )

if installed('groups'):    
    urlpatterns += patterns('',
        (r'^groups/', include('groups.urls')),
    )

if installed('sentry'):
    urlpatterns += patterns('',
        (r'^sentry/', include('sentry.web.urls')),
    )

if installed('nexus'):
    import nexus
    nexus.autodiscover()

    urlpatterns += patterns('',
        (r'^admin/', include('nexus.site.urls')),
    )
else:
    urlpatterns += patterns('', 
        url(r'^admin/', include(admin.site.urls)),
    )

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

app/hr/models.py
from datetime import datetime
from django.conf import settings
from django.db import models
from django.template import Template, Context
from django.contrib.auth.models import User
from eve_api.models import EVEPlayerCharacter, EVEPlayerCorporation
from eve_api.app_defines import *
from hr.app_defines import *

class Application(models.Model):
    """ Person's application to a corporation """

    user = models.ForeignKey(User, blank=False, verbose_name="User")
    character = models.ForeignKey(EVEPlayerCharacter, blank=False,
                                  verbose_name="Character")
    corporation = models.ForeignKey(EVEPlayerCorporation, blank=False,
                                    verbose_name="Applying to Corporation")
    status = models.IntegerField(choices=APPLICATION_STATUS_CHOICES,
                                     default=APPLICATION_STATUS_NOTSUBMITTED,
                                     verbose_name="Status",
                                     help_text="Current status of this application request.")
    application_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")

    @models.permalink
    def get_absolute_url(self):
        return ('hr.views.view_application', [self.id])

    @property
    def blacklisted(self):
        return len([x for x in self.blacklist_values if x.level == BLACKLIST_LEVEL_BLACKLIST]) > 0

    @property
    def blacklist_values(self):
        if not hasattr(self, '_blcache'):
            from hr.utils import blacklist_values
            self._blcache = blacklist_values(self.user)
        return self._blcache

    @property
    def last_action(self):
        if self.audit_set.count():
            return self.audit_set.all().order_by('-date')[0]
        return None

    @property
    def alt_application(self):
        if EVEPlayerCharacter.objects.filter(corporation=self.corporation, eveaccount__user=self.user).count() > 0:
            return True
        return False

    def save(self, *args, **kwargs):

        user = kwargs.pop('user', None)
        try:
            old_instance = Application.objects.get(id=self.id)
            if not (old_instance.status == int(self.status)):
                event = Audit(application=self)
                event.user = user
                event.event = AUDIT_EVENT_STATUSCHANGE

                # Save the application so we can get a up to date status
                super(Application, self).save(*args, **kwargs)
                new_instance = Application.objects.get(id=self.id)

                event.text = "Status changed from %s to %s" % (old_instance.get_status_display(), new_instance.get_status_display())
                event.save()
        except:
            pass

        super(Application, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.character.name

    class Meta:
        permissions = (
            ("can_accept", "Can accept / reject applications"),
            ("can_view_all", "Can view all applications"),
            ("can_view_corp", "Can view corp applications"),
        )

class Recommendation(models.Model):
    """ User recommendation for a application """

    user = models.ForeignKey(User, blank=False, verbose_name="User")
    user_character = models.ForeignKey(EVEPlayerCharacter, blank=False, verbose_name="Recommender")
    application = models.ForeignKey(Application, blank=False, verbose_name="Recommended Application")
    recommendation_date = models.DateTimeField(auto_now_add=True, verbose_name="Recommendation Date")

    @models.permalink
    def get_absolute_url(self):
        return ('hr.views.view_application', [self.application.id])

    @property
    def recommended_user(self):
        return self.application.user

    @property
    def is_valid(self):
        diff = self.recommendation_date - self.user_character.corporation_date
        if self.user_character.eveaccount_set.count() and self.user_character.eveaccount_set.all()[0].api_status == API_STATUS_OK and diff.days >= settings.HR_RECOMMENDATION_DAYS and self.user_character.corporation == self.application.corporation:
            return True
        return False

    def __unicode__(self):
        return self.user_character.name


class Audit(models.Model):
    """ Auditing information regarding a application """

    application = models.ForeignKey(Application, blank=False, verbose_name="Application")
    user = models.ForeignKey(User, blank=True, verbose_name="User")
    event = models.IntegerField(choices=AUDIT_EVENT_CHOICES,
                                     verbose_name="Event Type",
                                     help_text="Type of audit event")
    text = models.TextField(blank=False, verbose_name="Event Text",
                                     help_text="Detailed event text")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Event Date")

    @models.permalink
    def get_absolute_url(self):
        return ('hr.views.view_application', [self.application.id])

    def __unicode__(self):
        return u"(%s) %s: %s" % (self.get_event_display(), self.user, self.text)

    class Meta:
        get_latest_by = 'date'
        ordering = ['date']

class BlacklistSource(models.Model):
    """ Blacklist Source """

    name =  models.CharField("Blacklist Source Name", max_length=255, blank=False)
    ticker = models.CharField("Blacklist Source Ticker", max_length=255, blank=False)

    def __unicode__(self):
        return self.name


class Blacklist(models.Model):
    """ Blacklisted entries, stops people who match the criteria from applying """

    type = models.IntegerField(choices=BLACKLIST_TYPE_CHOICES,
                                     verbose_name="Blacklisted Type",
                                     help_text="Type of entity to be blacklisted")
    level = models.IntegerField(choices=BLACKLIST_LEVEL_CHOICES,
                                     verbose_name="Blacklist Level",
                                     help_text="Level of blacklisting", default=BLACKLIST_LEVEL_BLACKLIST)
    value = models.CharField("Blacklisted Value", max_length=255, blank=False)
    reason = models.TextField(blank=False, verbose_name="Reason",
                                     help_text="Reason that the entity was blacklisted")
    expiry_date = models.DateTimeField(verbose_name="Expiry Date", blank=False, null=True,
                                     help_text="Date to expire this entry")
    source = models.ForeignKey(BlacklistSource, blank=False, verbose_name="Source")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created Date")
    created_by = models.ForeignKey(User, blank=False, verbose_name="Created By")

    def __unicode__(self):
        return u'%s: %s' % (self.get_type_display(), self.value)


class ApplicationConfig(models.Model):
    """ Defines configuration settings for applications """

    corporation = models.OneToOneField(EVEPlayerCorporation, blank=False, verbose_name="Corporation", related_name="application_config")
    is_accepting = models.BooleanField(verbose_name="Accepting Applications",
                                       help_text="Defines if the corporation is accepting applications")
    api_required = models.IntegerField(choices=API_KEYTYPE_CHOICES, default=1, verbose_name="API Key Type",
                                       help_text="This defines the type of API key needed to create a application")
    api_accessmask = models.IntegerField(verbose_name="Minimum Access Level",
                                       help_text="Defines the minimum level API accepted as valid, provided as a CAK accessMask")
    api_view = models.BooleanField(verbose_name="View Applicant APIs",
                                       help_text="This allows HR staff to see the applicant's API keys")

    def __unicode__(self):
        return u'%s' % self.corporation

    class Meta:
        verbose_name = 'Application Config'
        verbose_name_plural = 'Application Configs'
        ordering = ['corporation']


class TemplateMessage(models.Model):
    """ A message template for communications in applications """

    config = models.ForeignKey(ApplicationConfig, related_name="templates")
    name = models.CharField("Template Name", max_length="200", blank=False, null=False)
    text = models.TextField("Text", blank=False, null=False)

    def render_template(self, values):
        return Template(self.text).render(Context(values))

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Template Message'
        verbose_name_plural = u'Template Messages'
        ordering = ['config', 'name']

app/reddit/models.py
from datetime import datetime, date
import urllib

from django.utils import simplejson as json
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now, utc

from reddit.api import Comment


class RedditAccount(models.Model):
    """
    Represents a User ID on Reddit

    This model can be populated by API update:

    >>> from reddit.models import RedditAccount
    >>> mod = RedditAccount()
    >>> mod.username = 'nik_doof'
    >>> mod.api_update()
    >>> mod.reddit_id
    u'1axok'
    """

    user = models.ForeignKey(User, blank=True, null=True)

    username = models.CharField("Reddit Username", max_length=32, blank=False, unique=True)
    reddit_id = models.CharField("Reddit ID", max_length=32, help_text="Reddit's unique id for this user")

    link_karma = models.IntegerField("Link Karma", help_text="Number of link karma")
    comment_karma = models.IntegerField("Comment Karma", help_text="Number of comment karma")
    validated = models.BooleanField("Validated", help_text="Indicates if the user has been validated")

    date_created = models.DateTimeField("Date Created")
    last_update = models.DateTimeField("Last Update from API")

    def api_update(self):
        try:
            jsondoc = json.load(urllib.urlopen("http://reddit.com/user/%s/about.json" % self.username))
        except:
            raise self.DoesNotExist

        if 'error' in jsondoc:
            raise self.DoesNotExist
        
        data = jsondoc['data']
        
        self.link_karma = int(data['link_karma'])
        self.comment_karma = int(data['comment_karma'])
        self.reddit_id = unicode(data['id'], 'utf-8')

        self.date_created = datetime.fromtimestamp(data['created_utc']).replace(tzinfo=utc)
        self.last_update = now()

    def recent_posts(self):
        """ Returns the first page of posts visible on the user's profile page """

        try:
            jsondoc = json.load(urllib.urlopen("http://reddit.com/user/%s.json" % self.username))
        except:
            raise self.DoesNotExist
        
        posts = []
        for item in jsondoc['data']['children']:
            if item['kind'] == 't1':
                posts.append(Comment(item['data']))
            elif item['kind'] == 't3':
                posts.append(item['data'])

        return posts

    @property
    def is_valid(self):
        if not self.date_created:
            return False

        # Account 3 months old?
        if (date.today() - self.date_created.date()).days >= 90:
            return True

        # Account created after 9/2/10 and before 13/2/10
        if self.date_created.date() >= date(2010, 2, 9) and self.date_created.date() <= date(2010, 2, 13):
            return True

        return False


    class Meta:
        app_label = 'reddit'
        ordering = ['username']
        verbose_name = 'Reddit Account'
        verbose_name_plural = 'Reddit Accounts'

    def __unicode__(self):
        return self.username

app/hr/templates/hr/applications/accept.html
{% extends "base.html" %}

{% block title %}Accept Application{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Accept Application</h1>
</div>


<p>Fill in a note you want to send to the user.</p>
<form action="{% url hr-acceptapplication application.id %}" method="post">
<fieldset>
  {% include "formtools/formerror.html" %}
  {% include "formtools/formfield.html" with field=form.text class="xxlarge" %}
  {% include "formtools/formfield.html" with field=form.template %}
  {% csrf_token %}
  <input type="submit" value="Add" class="btn primary"/>
</fieldset>

</form>
{% endblock %}

app/hr/templates/hr/applications/add.html
{% extends "base.html" %}

{% block title %}Create Application{% endblock %}

{% block content %}

<div class="page-header">
  <h1>New Application</h1>
</div>

<p>Select the character you wish to apply with, then the corporation you wish to apply for.</p>

<form action="{% url hr-addapplication %}" method="post">
<fieldset>
  {% include "formtools/formerror.html" %}
  {% include "formtools/formfield.html" with field=form.character %}
  {% include "formtools/formfield.html" with field=form.corporation %}
  {% csrf_token %}
  <input type="submit" value="Create Application" class="btn primary"/>
</fieldset>
</form>

{% endblock %}

app/hr/templates/hr/applications/add_message.html
{% extends "base.html" %}

{% block title %}Send Message to Applicant{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Add Message</h1>
</div>

<form action="{% url hr-addmessage application.id %}" method="post">
<fieldset>
  {% include "formtools/formerror.html" %}
  {% include "formtools/formfield.html" with field=form.text class="xxlarge" %}
  {% if form.template %}{% include "formtools/formfield.html" with field=form.template %}{% endif %}
  {% csrf_token %}
  <input type="submit" value="Add" class="btn primary"/>
</fieldset>
</form>
{% endblock %}

app/hr/templates/hr/applications/add_note.html
{% extends "base.html" %}

{% block title %}Add Note to Application{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Add Staff Note</h1>
</div>

<form action="{% url hr-addnote application.id %}" method="post">
<fieldset>
  {% include "formtools/formerror.html" %}
  {% include "formtools/formfield.html" with field=form.text class="xxlarge" %}
  {% csrf_token %}
  <input type="submit" value="Add" class="btn primary"/>
</fieldset>
</form>
{% endblock %}

app/hr/templates/hr/applications/noadd.html
{% extends "base.html" %}

{% block title %}Create Application{% endblock %}

{% block content %}
<p>Unfortunatly, no Corporations are accepting applications at the moment.</p>
{% endblock %}

app/hr/templates/hr/applications/reject.html
{% extends "base.html" %}

{% block title %}Reject Application{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Reject Application</h1>
</div>

<p>Fill in the rejection reason below, please note, this will be sent out to the user.</p>
<form action="{% url hr-rejectapplication application.id %}" method="post">

<fieldset>
  {% include "formtools/formerror.html" %}
  {% include "formtools/formfield.html" with field=form.text class="xxlarge" %}
  {% include "formtools/formfield.html" with field=form.template %}
  {% csrf_token %}
  <input type="submit" value="Reject" class="btn error"/>
</fieldset>


</form>
{% endblock %}

app/hr/templates/hr/applications/view.html
{% extends "base.html" %}

{% load humanize %}
{% load if_extra %}
{% load installed %}
{% load naturaltimediff %}
{% load gargoyle_tags %}

{% block title %}View Application{% endblock %}

{% block content %}
<div class="page-header">
<h1>Application - {{ app.character }} to {{ app.corporation }} </h1>
</div>

<ul>
<li>Applying Auth User: <a href="{% url sso-viewuser app.user %}">{{ app.user.username }}</a></li>
<li>Applying Character: <a href="{% url eveapi-character app.character.pk %}">{{ app.character.name }}</a></li>
<li>Applying To: <a href="{% url eveapi-corporation app.corporation.pk %}">{{ app.corporation.name }}</a></li>
<li>Application Status: {{ app.get_status_display }}</li>
{% if hrstaff %}
<li>Blacklist Status: <b>{% if app.blacklisted %}<span class="label important">>BLACKLISTED</span>{% else %}<span class="label success">OK</span>{% endif %}</b></li>
{% endif %}
</ul>

{% ifnotequal app.status 5 %}
{% ifnotequal app.status 2 %}
<h3>Actions</h3>

<p>
{% if app.status < 1 %}
<a class="btn success" href="{% url hr-updateapplication app.id 1 %}">Submit Application</a>
{% else %}
<a class="btn" href="{% url hr-updateapplication app.id 0 %}">Withdraw Application</a>
{% endif %}
<a class="btn" href="{% url hr-addmessage app.id %}">Add Message</a>
{% if hrstaff %}
<a class="btn" href="{% url hr-addnote app.id %}">Add Staff Note</a>
{% if app.status < 2 or app.status = 4 or app.status = 6 %}
{% if perms.hr.can_accept %}
<a class="btn error" href="{% url hr-rejectapplication app.id %}">Reject Application</a>
{% ifequal app.blacklisted 0 %}
<a class="btn success" href="{% url hr-acceptapplication app.id %}">Accept Application</a>
{% endifequal %}
{% endif %}
{% ifnotequal app.status 4 %}
<a class="btn" href="{% url hr-updateapplication app.id 4 %}">Mark as In Query</a>
{% endifnotequal %}
{% ifnotequal app.status 6 %}
<a class="btn" href="{% url hr-updateapplication app.id 6 %}">Flag for Review</a>
{% endifnotequal %}
{% endif %}
{% ifequal app.status 3 %}
<a class="btn success" href="{% url hr-updateapplication app.id 5 %}">Mark as Complete</a>
{% endifequal %}
{% endif %}
</p>
{% endifnotequal %}
{% endifnotequal %}

{% if audit %}
<h3>Event Log</h3>

<table class="zebra-striped">
  <thead>
    <tr><th width="50px">Event Type</th><th width="75px">User</th><th width="50px">Date</th><th>Event Details</th></tr>
  </thead>
  <tbody>
    {% for a in audit %}
    <tr><td>{{ a.get_event_display }}</td><td><a href="{% url sso-viewuser a.user.username %}">{{ a.user.profile.all.0.primary_character }}</a></td><td>{{ a.date|date:"Y/m/d H:i:s" }}</td><td>{{ a.text|linebreaks }}</td></tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if hrstaff %}
{% if app.blacklist_values %}
<h3>Blacklist Triggers</h3>

<table class="zebra-striped">
  <thead>
    <tr><th>Blacklist Type</th><th>Blacklisted Value</th><th>Level</th><th>Reason</th><th>Source</th></tr>
  </thead>
  <tbody>
    {% for a in app.blacklist_values %}
    <tr><td>{{ a.get_type_display }}</td><td>{{ a.value }}</td><td>{{ a.get_level_display }}</td><td>{{ a.reason }}</td><td>{{ a.source }}</td></tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endif %}

{% if app.recommendation_set.all %}
<h3>Recommendations</h3>

<table class="zebra-striped">
  <thead>
    <tr><th>User</th><th>Character</th><th>Corporation</th><th>Valid Recommendation</th><th>Total User Recomendations</th></tr>
  </thead>
  <tbody>
    {% for rec in app.recommendation_set.all %}
    <tr><td><a href="{% url sso-viewuser rec.user %}">{{ rec.user }}</a></td>
      <td><a href="{% url eveapi-character rec.user_character.pk %}">{{ rec.user_character }}</a></td>
      <td><a href="http://evemaps.dotlan.net/corp/{{ rec.user_character.corporation.name }}">{{ rec.user_character.corporation }}</a></td>
      <td>{% if rec.is_valid %}<font color="green">Yes</font>{% else %}<font color="red">No</font>{% endif %}</td>
      <td>{{ rec.user.recommendation_set.all.count }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if hrstaff %}
{% if app.corporation.application_config.api_view %}
<h3>API Keys</h3>

<table>
  <thead>
    <tr><th>User ID</th><th>API Key</th><th>Description</th><th>Type</th><th>Active</th><th>Last Updated</th></tr>
  </thead>
  <tbody>
    {% for acc in app.user.eveaccount_set.all %}
    <tr><td>{{ acc.api_user_id }}</td>
      <td>{{ acc.api_key }}</td>
      <td>{{ acc.description }}</td>
      <td>{{ acc.get_api_keytype_display }}</td>
      <td id="api-status-{{ acc.api_user_id }}">{{ acc.get_api_status_display }}</td>
      <td id="api-time-{{ acc.api_user_id }}">{{ acc.api_last_updated|naturaltimediff }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<h3>EVE Characters</h3>

<table id="characters">
  <thead>
    <tr><th>Character</th><th>Corp / Alliance</th><th>ISK</th><th>SP</th><th>Training</th><th>Links</th></tr>
  </thead>
  <tbody>
    {% for acc in app.user.eveaccount_set.all %}
    {% for char in acc.characters.all %}
    <tr{% if char.id == app.character.id %} style="background-color: #FFE8D0"{% endif%}><td><a href="{% url eveapi-character char.pk %}">{{ char.name }}</a></td>
      <td><a href="http://evemaps.dotlan.net/corp/{{ char.corporation }}">{{ char.corporation }}</a>{% if char.corporation.alliance %} / 
        <a href="http://evemaps.dotlan.net/alliance/{{ char.corporation.alliance }}">{{ char.corporation.alliance }}</a>{% endif %}
      </td>
      <td style="text-align: right;">{{ char.balance|intcomma }}</td>
      <td style="text-align: right;">{{ char.total_sp|intcomma }}</td>
      <td>{% if char.current_training %}{{ char.current_training.skill.name }} to Level {{ char.current_training.in_training }}{% endif %}</td>
      <td>{% if request.is_igb %}<a href="javascript:CCPEVE.showInfo(1377, {{ char.id }})">Show In Eve</a> / {% endif %}<a href="https://gate.eveonline.com/Profile/{{ char.name }}/">EveGate Profile</a> / <a href="http://eve-search.com/search/author/{{ char.name }}">EveSearch</a> / <a href="https://forums.eveonline.com/default.aspx?g=search&postedby={{ char.name}}">EVEGate Forums</a></td>
    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>


{% if "reddit"|installed %}
{% ifswitch reddit %}
{% if app.user.redditaccount_set.all %}
<h3>Reddit Accounts</h3>

<table class="zebra-striped" id="reddit">
  <thead>
    <tr><th>Account</th><th>Karma</th><th>Validated</th><th>Creation Date</th><th>Matches Criteria?</th><th>Links</th></tr>
  </thead>
  <tbody>
    {% for acc in app.user.redditaccount_set.all %}
    <tr><td><a href="http://reddit.com/user/{{ acc.username }}/">{{ acc.username }}</a></td>
      <td>{{ acc.link_karma }} / {{ acc.comment_karma }}</td>
      <td>{% if acc.validated %}<span class="label success">Validated</span>{%else %}<span class="label warning">NOT VALIDATED</span>{% endif %}</td>
      <td>{{ acc.date_created }}</td>
      <td>{% if acc.is_valid %}<font color="green">Yes</font>{% else %}<font color="red">No</font>{% endif %}</td>
      <td><a href="http://metareddit.com/stalk?user={{ acc.username}}">Metareddit</a> / <a href="http://www.nossquad.com/EVETools/RedditUserInfo.aspx?username={{ acc.username }}">User Info</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h3>Recent Reddit Posts</h3>

<span id="loadlink">
<a href="javascript:redditposts()" class="btn">Load recent Reddit posts</a>
</span>

<script type="text/javascript">
function createRequestObject() {
    var ro;
    var browser = navigator.appName;
    if(browser == "Microsoft Internet Explorer"){
        ro = new ActiveXObject("Microsoft.XMLHTTP");
    }else{
        ro = new XMLHttpRequest();
    }
    return ro;
}

var http = createRequestObject();

function redditposts(action) {
    http.open('get', '{% url reddit-commentsjson %}?userid={{ app.user.id }}');
    http.onreadystatechange = handleResponse;
    http.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    http.send(null);
}

function handleResponse() {
    if(http.readyState == 4){
        var response = eval('(' + http.responseText + ')');
        var update = new Array();

        document.getElementById('loadlink').style.display = 'none';

        var out = '';
        for (var obj in response['posts']) {
            if (response['posts'][obj]['kind'] == 2) {
                var out = out + "<p><b><a href=\"http://reddit.com" + response['posts'][obj]['permalink'] + "\">" + response['posts'][obj]['title'] + "</a></b> - (/r/" + response['posts'][obj]['subreddit']+ ")</p>";
            } else {
                var out = out + "<p>" + response['posts'][obj]['body'] + "<br/><b>/r/" + response['posts'][obj]['subreddit'] + "</b> <a href=\"" + response['posts'][obj]['permalink'] + "\">Permalink</a></p>";
            }
        }
        document.getElementById('redditposts').innerHTML = out;
    }
}
</script>

<div id="redditposts">
</div>
{% endif %}
{% endifswitch %}
{% endif %}
{% endif %}
{% endblock %}

app/hr/templates/hr/applications/view_list.html
{% extends "base.html" %}

{% block title %}Applications{% endblock %}

{% block content %}

<div class="page-header">
  <h1>You Applications</h1>
</div>  

{% if applications %}
<p>This is a list of all your applications. The current status of each application is shown in the Application Status field.</p>

<table class="zebra-striped" id="applications">
  <tr><th>Application ID</th><th>Character</th><th>Corporation</th><th>Application Status</th></tr>
  {% for app in applications %}
  <tr><td><a href="{% url hr-viewapplication app.id %}">{{ app.id }}</a></td>
    <td>{{ app.character }}</td>
    <td>{{ app.corporation }}</td>
    <td>{{ app.get_status_display }}</td>
  </tr>
  {% endfor %}
</table>

{% else %}
<p>You have no current applications</p>
{% endif %}

<p><a href="{% url hr-addapplication %}" class="btn">Apply to a corporation</a></p>

{% endblock %}